# Cloudflare Pages configuration for JFlix
name = "jflix"
compatibility_date = "2025-05-20"

# Build configuration
[build]
command = "npm run build"

# Environment variables
[vars]
NODE_VERSION = "18"

# Routes configuration
[[routes]]
pattern = "/movies/:id*"
script = "pages-functions.js"

[[routes]]
pattern = "/tvshows/:id*"
script = "pages-functions.js"

[[routes]]
pattern = "/*"
script = "pages-functions.js"

# Headers for better security and performance
[[headers]]
pattern = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
pattern = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
pattern = "/images/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
