# wrangler.toml - Configuration for Cloudflare Workers
name = "jflix"
compatibility_date = "2025-05-20"

# Configure Cloudflare Pages with Next.js compatibility
[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[site]
bucket = ".next/static"
entry-point = "./"

# Environment variables
[vars]
NEXT_RUNTIME = "edge"
